/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
    interface RouteList {
        'sanctum.csrf-cookie': [];
        home: [];
        user_home: [];
        profile_basic_update: [
            {
                name: 'uuid';
                required: false;
            },
        ];
        admin_home: [];
        admin_login: [];
        admin_account: [
            {
                name: 'uuid';
                required: false;
            },
        ];
        admin_store: [
            {
                name: 'uuid';
                required: false;
            },
        ];
        admin_account_delete: [
            {
                name: 'uuid';
                required: true;
            },
        ];
        admin_account_list: [];
        admin_dashboard: [];
        admin_logout: [];
        attribute_type_list: [];
        attribute_type_form: [
            {
                name: 'id';
                required: false;
            },
        ];
        attribute_type_store: [
            {
                name: 'id';
                required: false;
            },
        ];
        attribute_type_destroy: [
            {
                name: 'id';
                required: true;
            },
        ];
        attribute_list: [];
        attribute_form: [
            {
                name: 'key';
                required: false;
            },
        ];
        attribute_store: [
            {
                name: 'key';
                required: false;
            },
        ];
        attribute_destroy: [
            {
                name: 'key';
                required: true;
            },
        ];
        profile_create_form: [];
        profile_create_store: [];
        admin_profile_list: [];
        admin_profile_update_form: [
            {
                name: 'uuid';
                required: true;
            },
        ];
    }
}
export {};
